#include: package:effective_dart/analysis_options.yaml
#include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    lines_longer_than_80_chars: false
    camel_case_types: true
    always_declare_return_types: true

    await_only_futures: true
    unawaited_futures: true
    comment_references: true

    prefer_void_to_null: true

    void_checks: true

analyzer:
  exclude: lib/templates/*.dart
