name: fsm2
version: 2.0.1
homepage: https://github.com/bsutton/fsm2
description: FSM2 provides an implementation of the core design aspects of the UML state diagrams allowing both declarative transitions and dynamic transitions along with Guard Conditions.
environment: 
  sdk: '>=2.12.0-259.9.beta <3.0.0'
dependencies: 
  args: ^2.0.0
  completer_ex: ^2.0.0
  dcli: ^0.50.0
  meta: ^1.3.0
  path: ^1.8.0
  stacktrace_impl: ^2.0.0
  synchronized: ^3.0.0
  tree_iterator: ^2.0.0
dev_dependencies: 
  build_runner: ^1.0.0
  lint: ^1.0.0
  mockito: ^5.0.0-0
  test: ^1.16.2
executables: 
  fsm2: 
