name: fsm2
version: 2.0.7
publish_to: none
homepage: https://noojee.gitbook.io/fsm2/
documentation: https://noojee.gitbook.io/fsm2/
description: FSM2 provides an implementation of the core design aspects of the UML state diagrams allowing both declarative transitions and dynamic transitions along with Guard Conditions.
repository: https://github.com/bsutton/fsm2
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  completer_ex: ^3.0.0
  logger: ^1.0.0
  meta: ^1.6.0
  path: ^1.7.0
  stacktrace_impl: ^2.0.1
  synchronized: ^3.0.0
  tree_iterator: ^2.0.0
dev_dependencies:
  lint: ^1.0.0
  mockito: ^5.0.0
  test: ^1.0.0
